// Code generated by mapgen; DO NOT EDIT.

package testdata

import (
	"github.com/nduyhai/mapgen/test/fancy"
)

// addressDtoMapper is a generated mapper implementation.
type addressDtoMapper struct{}

// ToDTO maps from *fancy.Address to *AddressDto.
func (m *addressDtoMapper) ToDTO(source *fancy.Address) *AddressDto {
	target := &AddressDto{}

	// Apply field mappings
	// Ignoring field:
	target.Street = source.Street
	// Ignoring field:

	return target
}
