// Code generated by mapgen; DO NOT EDIT.

package testdata

// defaultMapper is a generated mapper implementation.
type defaultMapper struct{}

// ToTarget maps from *SimpleSource to *SimpleTarget.
func (m *defaultMapper) ToTarget(source *SimpleSource) *SimpleTarget {
	target := &SimpleTarget{}
	// Default behavior: copy all fields with matching names from source to target
	target.ID = source.ID
	target.Name = source.Name
	target.Email = source.Email
	target.CreatedAt = source.CreatedAt

	return target
}
