// Code generated by mapgen; DO NOT EDIT.

package testdata

import (
	"github.com/nduyhai/mapgen/test/bootiful"
)

// userMapper is a generated mapper implementation.
type userMapper struct{}

// ToDTO maps from *User to *bootiful.UserDTO.
func (m *userMapper) ToDTO(source *User) *bootiful.UserDTO {
	target := &bootiful.UserDTO{}

	// Apply field mappings
	target.Name = source.UserName
	target.CreatedAt = TimeToUnix(source.CreatedAt)
	target.RetrievedAt = bootiful.GetCurrentTime()
	target.CreatedAt = TimeToUnix(source.CreatedAt)

	return target
}
